# Generated by Django 3.1.7 on 2021-03-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'verbose_name': 'Contract type', 'verbose_name_plural': 'Contract types'},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='date_started',
        ),
    ]
