# Generated by Django 3.1.7 on 2021-03-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
        ('practice', '0002_auto_20210312_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.occurrence')),
                ('attendance', models.CharField(choices=[('attended', 'Attended'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], max_length=16)),
            ],
            bases=('schedule.occurrence',),
        ),
        migrations.CreateModel(
            name='PractitionerHolidayPeriod',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='practice.timestampedmodel')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practitioner')),
            ],
            bases=('practice.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='ClientHolidayPeriod',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='practice.timestampedmodel')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.client')),
            ],
            bases=('practice.timestampedmodel',),
        ),
    ]
