# Generated by Django 3.1.7 on 2021-03-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_clientholidayperiod_practitionerholidayperiod_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alias',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
